[package]
name = "Server"
version = "0.1.0"
authors = ["bdyer <bdyer-contractor@cars.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.8"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
serde = "1.0.101"
